// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/AirHelp/autoscaler/probe/nginx (interfaces: NginxClient)

// Package nginxMock is a generated GoMock package.
package nginxMock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNginxClient is a mock of NginxClient interface.
type MockNginxClient struct {
	ctrl     *gomock.Controller
	recorder *MockNginxClientMockRecorder
}

// MockNginxClientMockRecorder is the mock recorder for MockNginxClient.
type MockNginxClientMockRecorder struct {
	mock *MockNginxClient
}

// NewMockNginxClient creates a new mock instance.
func NewMockNginxClient(ctrl *gomock.Controller) *MockNginxClient {
	mock := &MockNginxClient{ctrl: ctrl}
	mock.recorder = &MockNginxClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNginxClient) EXPECT() *MockNginxClientMockRecorder {
	return m.recorder
}

// GetActiveConnections mocks base method.
func (m *MockNginxClient) GetActiveConnections(arg0 context.Context, arg1 string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveConnections", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveConnections indicates an expected call of GetActiveConnections.
func (mr *MockNginxClientMockRecorder) GetActiveConnections(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveConnections", reflect.TypeOf((*MockNginxClient)(nil).GetActiveConnections), arg0, arg1)
}
