name: Pull request obligatory checks

on:
  - pull_request

jobs:
  RunTests:
    name: run tests
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.22
      - run: go mod download
      - run: go test -v -cover ./...
