name: Build and Publish

on:
  push:
    tags:
      - '*'

jobs:
  BuildAndPublishDockerImage:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            airhelp/autoscaler
          tags: |
            type=semver,pattern={{version}}
            type=sha,format=long,prefix=
            latest

      - name: Build image and push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
