name: "Stale issues and pull requests"

on:
  schedule:
    - cron: "0 10 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v4
      with:
        days-before-issue-stale: 30
        days-before-pr-stale: 14
        days-before-issue-close: 7
        days-before-pr-close: 7
        exempt-issue-labels: "dependabot"
        exempt-pr-labels: "dependabot"
